# config.yaml
defaults:
  compression: "snappy"
  chunk_size: 100000

paths:
  base_dir: "data"
  raw_dir: "${paths.base_dir}/raw"
  staging_dir: "${paths.base_dir}/staging"
  output_dir: "${paths.base_dir}/processed"

datasets:
  yelp:
    base_dir: "${paths.raw_dir}/Yelp JSON/yelp_dataset"
    business:
      raw_file: "yelp_academic_dataset_business.json"
      staging_file: "yelp_business.parquet"
      map_file: "yelp_city_zip_consensus.parquet"
      columns_to_keep: ["business_id", "name", "city", "state", "stars", "review_count", "categories", "postal_code"]
      processing:
        chunk_size: 50000  
        sample_pct: 1.0    
  
  irs:
    base_dir: "${paths.raw_dir}/zipcode2022"
    raw_file: "22zpallagi.csv"
    staging_file: "irs_silver.parquet"
    # agi_stub: Adjusted Gross Income
    # n1: number of (tax) returns
    # n2: number of individuals
    # mars2: # of joint returns
    columns_to_keep: ["zipcode", "state", "agi_stub", "n1", "n2", "mars2"]

  yelp_irs:
    staging_file: "yelp_irs_joined.parquet"

ml:
  cluster_features: [
    'ratio_under_25k', 'ratio_25k_to_50k', 'ratio_50k_to_75k', 'ratio_75k_to_100k', 
    'ratio_100k_to_200k', 'ratio_over_200k', 
    'marriage_ratio_under_25k', 'marriage_ratio_25k_to_50k', 'marriage_ratio_50k_to_75k', 
    'marriage_ratio_75k_to_100k', 'marriage_ratio_100k_to_200k', 'marriage_ratio_over_200k'
  ]
  num_clusters: 5
  cluster_staging_file: "clusters.parquet"
  target_categories: [
    ["Restaurants", "Food"],
    ["Shopping"],
    ["Health & Medical"],
    ["Beauty & Spas"],
    ["Bars", "Nightlife"]
  ]
  quantile: 0.95



